---
- name: Remove all apache, php, and nginx software
  ansible.builtin.apt:
    name:
      - apache2*
      - php*
      - nginx*
    state: absent
    purge: true
    autoremove: true
  become: true
