---
- name: Install mysql-server
  ansible.builtin.apt:
    name: 
      - mysql-server
      - python3-mysqldb
    state: present
  become: true

- name: Enable and start mysql
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true
  become: true

- name: Delete anonymous user
  community.mysql.mysql_user: 
    name: ""
    host_all: true
    state: absent
  become: true

- name: Delete hostname-based root user
  community.mysql.mysql_user:
    name: root
    host: "{{ansible_nodename}}"
    state: absent
  become: true

- name: Remove test database
  community.mysql.mysql_db:
    name: test
    state: absent
  become: true

- name: Create snipeit database
  community.mysql.mysql_db:
    name: "{{ snipe_db_database }}"
    state: present
  become: true

- name: Create snipeit user
  community.mysql.mysql_user:
    name: "{{ snipe_db_username }}"
    password: "{{ snipe_db_password }}"
    priv: "{{ snipe_db_database }}.*:ALL"
    state: present
  become: true
