---
- name: Install NGINX
  ansible.builtin.include_role:
    name: nginxinc.nginx_core.nginx
  vars:
    ansible_become: yes

- name: Configure NGINX
  ansible.builtin.include_role:
    name: nginxinc.nginx_core.nginx_config
  vars:
    ansible_become: yes
    nginx_config_main_template_enable: true
    nginx_config_main_template:
      template_file: nginx.conf.j2
      deployment_location: /etc/nginx/nginx.conf
      backup: false
      config:
        main:
        user:
          username: www-data
          group: www-data
        http:
          include:
            - /etc/nginx/conf.d/*.conf
            - /etc/nginx/mime.types

- name: Configure NGINX for Snipe-IT
  ansible.builtin.template:
    src: templates/snipeit.conf.j2
    dest: /etc/nginx/conf.d/snipeit.conf
    owner: root
    group: root
    mode: '0444'
  become: yes
  notify: restart nginx

- name: Enable and start nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  become: yes