---
# handlers file for snipe-it

- name: restart mysql
  become: true
  ansible.builtin.service:
    name: mysql
    state: restarted

- name: restart apache
  become: true
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: restart nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted
